### ISSUE TITLE
Silhouetteのタスク完了時に次のタスクを自動開始したい

### ISSUE THREAD

**Issue by wp041** [tadashi-aikawa/silhouette#1]
Silhouette、非常に便利に使わせて頂いております。

## 詳細
`cycle bullet/checkbox`や`push timer`コマンドを入力した際、入力行から一つ下の行のタスクを同時に開始したいです。

## 目的
- タイマーの起動忘れ防止
- 即時起動によってサボることを防止する

## 背景
一つのタスクが終わったことで休憩を始めてしまうのでこの機能が切実に欲しいです……
勝手なお願いですが是非ご一考ください

**Comment by tadashi-aikawa** [comment]
@wp041 
FBありがとうございます。

> cycle bullet/checkboxやpush timerコマンドを入力した際、入力行から一つ下の行のタスクを同時に開始したい

『 `cycle bullet/checkbox` でタイマーを終了したときに、1つ下のタスクがあったら開始する』はアリだと思います。ただ、コマンドは別にすると思います。

SilhouetteのIssueとした方が自然なので、そちらに移動させていただきますね。

**Comment by tadashi-aikawa** [comment]
@wp041 
こんな感じでいかがでしょう?

https://github.com/tadashi-aikawa/silhouette/assets/9500018/c1e9f837-8a4a-46fa-b75b-8ff624a912dd

コマンドは `cycle bullet/checkbox` です。オプションを追加して、そちらで制御しようと思います。

**Comment by tadashi-aikawa** [comment]
0.17.0でリリースしました。

https://github.com/tadashi-aikawa/silhouette/releases/tag/0.17.0

**Comment by wp041** [comment]
完璧です！ありがとうございます……
