### ISSUE TITLE
リアルタイムで経過時間を確認したい

### ISSUE THREAD

**Issue by wp041** [tadashi-aikawa/silhouette#2]
いつも便利に使わせて頂いております。

## 詳細
タスクの計測開始から何分経ったかをタブかなにかでリアルタイムに確認できるようにしていただきたいです。

## 目的
- 時間制限のあるタスクを扱いやすくしたい
- リアルタイムでどのくらいの時間がかかっているのかわかるようにしたい

**Comment by tadashi-aikawa** [comment]
@wp041 
起票ありがとうございます :)

ステータスバー(ウィンドウ右下)に表示はいかがでしょうか？ (文字は小さめになりますが…)

**Comment by wp041** [comment]
なるほど！私としては見れれば形式は何でも……という感じだったのでtadashi-aikawaさんにお任せいたします。ありがとうございます。

**Comment by tadashi-aikawa** [comment]
@wp041 
遅くなりましたが [v0.20.0](https://github.com/tadashi-aikawa/silhouette/releases/tag/0.20.0) で対応しました 🚀 

完全リアルタイムではありませんが、秒単位で計測が必要なシビアな要件でなければ問題ないと思っています。

※ やろうと思えば毎秒更新も不可能ではないですが、毎秒ファイル読み込みが必要になるためパフォーマンスを考えると望ましくないので実装していません

**Comment by wp041** [comment]
最高です！本当にありがとうございました。
