### ISSUE TITLE
`Silhouette: Insert current time` がインデントで行うとバレット(チェックボックス)の前で記録が挿入されてしまう.  

### ISSUE THREAD

**Issue by Akiyam-hub** [tadashi-aikawa/silhouette#3]
こんにちは.
新たに追加された`Silhouette: Insert current time`ですが
コマンドをインデントで行うとバレット(チェックボックス)の前で記録が挿入されてしまいます.

よろしければ確認のほどお願いしてもよろしいでしょうか?

- Mac OS 13.5.2
- Obsidian V1.4.14

![screencast 2023-10-08 11-04-03](https://github.com/tadashi-aikawa/silhouette/assets/53425804/ba243729-91e7-402a-bea8-2fe75d964cde)

**Comment by tadashi-aikawa** [comment]
@Akiyam-hub 
ご報告ありがとうございます。

タブでインデントする場合が考慮できていなかったようですので対応します。

**Comment by tadashi-aikawa** [comment]
@Akiyam-hub 
[v0.19.1](https://github.com/tadashi-aikawa/silhouette/releases/tag/0.19.1) で修正版をリリースしました 🚀
