### ISSUE TITLE
タスク化せずにそのまま出力する行設定機能の追加要望

### ISSUE THREAD

**Issue by neachi** [tadashi-aikawa/silhouette#4]
素晴らしいプラグインをありがとうございます。
毎日の繰り返しタスクをDailyNoteに追加するのに、非常に助かっています。

ひとつ機能追加の要望があるのですが、
`//から始まるコメント行` は無視する
というようなSilhouetteの機能と同じような感じで、
`\\から始まる行はタスク化せずにそのまま出力` みたいな機能があればありがたいなと思っています。
（ `\\`は例としてとりあえず書きました）

例を挙げますと、
``` text
06:00：ハミガキ,every day
06:00：筋トレ,every day
\\	- スクワット30回,every day
\\	- プランク60秒,every day
```
みたいな感じで「繰り返しタスクファイル」に登録した場合、
Silhouette: Insert tasksを実行したらDailyNote上では
``` text
- [ ] 06:00：ハミガキ
- [ ] 06:00：筋トレ
	- スクワット30回
	- プランク60秒
```
このような感じで、タスク化せずにインデントもそのまま出力されてくれたらありがたいなと思っています。
もしくは、「タスク化ではなく、バレットリストとして出力」でもありがたいです。

個人的になのですが、タスクの下に 補足的な感じで、上記のような書き方をしているタスクがいくつかあり、
現状は
``` text
06:00：ハミガキ,every day
06:00：筋トレ🔚スクワット30回🔚プランク60秒,every day
```
このような感じで「繰り返しタスクファイル」に登録しておいて、
DailyNoteにタスクを出力後に、自分で「🔚」の部分を改行した後、チェックボックスからバレットリストに手動で変更していってる感じでして、もしSilhouetteの方で、タスク化せずにそのまま出力できるようになれば、すごく便利だなと思っている次第です。

ご検討いただけましたらありがたいです。

最後に、素晴らしいプラグインの数々をありがとうございます！

**Comment by tadashi-aikawa** [comment]
@neachi 
以下はタスクになってしまうのでダメということですよね？

https://github.com/tadashi-aikawa/silhouette?tab=readme-ov-file#%E3%82%BF%E3%82%B9%E3%82%AF%E5%90%8D

タスク名に改行 ( `\n` ) を含める方法もありますが、見にくいので厳しいということですよね…

**Comment by neachi** [comment]
返事が遅くなってしまってすみません…！

> 以下はタスクになってしまうのでダメということですよね？

そうですねー…
それも試してみたのですが、Silhouette: Insert tasksを実行後にひとつひとつバレットリストに切り替えていっているのが結構手間でして、それならと「🔚」を入れておいてエディタで一括置換して対応してる感じなんです

毎日エディタで一度置換するだけなので、それほど手間ではないのですが、もしSilhouette側で実装が可能なら助かるなー…と思った次第でして…
ただ、実装が難しそうだったり、Silhouette的に不必要そうな機能な感じでしたら、ぜんぜん大丈夫です！

> タスク名に改行 ( \n ) を含める方法

っていうのがちょっと分からなかったのですが、
```text
06:00：ハミガキ,every day
06:00：筋トレ\nスクワット30回\nプランク60秒,every day
```
現状でもこんな感じで「繰り返しタスクファイル」に記載したら改行してくれる感じなんでしょうか？
（試してみましたが、うまくいかず…）

**Comment by tadashi-aikawa** [comment]
@neachi 

> 現状でもこんな感じで「繰り返しタスクファイル」に記載したら改行してくれる感じなんでしょうか？

確認してみたところダメそうでした😅 

> もしくは、「タスク化ではなく、バレットリストとして出力」でもありがたいです。

『タスク = `- [ ] ` でチェックリスト』という前提はありましたが、テンプレートから挿入する処理だけであればなんとかなりそうなので、対応してみます。

※ ただし、READMEには記載しない隠し仕様にすると思います。他に同様の要望・質問いただいた場合は公開する感じで

**Comment by neachi** [comment]
うわーすみません！実装していただけましたらすごく助かります
ありがとうございます！

**Comment by rakugakijin** [comment]
ありがとうございます。
自身のタスクではなく、家族や同僚のタスクを入力指定することがあり、「Task colector(TC)」で、都度逃げてました。この機能助かります。

**Comment by tadashi-aikawa** [comment]
@neachi @rakugakijin 
v0.21.0で対応しました。記載方法はリリースノートをご確認ください。
https://github.com/tadashi-aikawa/silhouette/releases/tag/0.21.0

**Comment by neachi** [comment]
ありがとうございますー！
試してみたら、まさに理想通りで最高です！
