### ISSUE TITLE
Insert current timeで開始時刻と終了時刻を両方打刻したい

### ISSUE THREAD

**Issue by masaki39** [tadashi-aikawa/silhouette#6]
いつもお世話になってます。
とても使いやすいプラグイン、ありがとうございます。

早速ですが、Insert current timeコマンドで既に打刻されている場合に、2回目以降の打刻で
19:00 - 20:00のような形式で打刻できないでしょうか。

また、Push timerとInsert current timeを同時実行できるようなコマンドもあるととても嬉しいです！

**Comment by tadashi-aikawa** [comment]
@masaki39 
FRありがとうございます :)

> Insert current timeコマンドで既に打刻されている場合に、2回目以降の打刻で 19:00 - 20:00のような形式で打刻できないでしょうか。

これはできると思います。別のコマンドにすると思いますが、やってみます。

> また、Push timerとInsert current timeを同時実行できるようなコマンドもあるととても嬉しいです！

複数のコマンドをまとめて実行するObsidianプラグインを使えば実現できると思います。それで不都合ある場合は、別のIssueでリクエストいただければと思います。(他にも需要があれば検討します)

**Comment by tadashi-aikawa** [comment]
> 別のコマンドにすると思いますが

確認しましたが、今のコマンドのまま提案いただいた挙動にしようと思います。

現状で複数回実行すると上書きではなく追記されますが、それは誰にも嬉しくなさそうなので... (上書きしているかなと思ってました 😅)

**Comment by tadashi-aikawa** [comment]
@masaki39 
[v0.23.0](https://github.com/tadashi-aikawa/silhouette/releases/tag/0.23.0) でリリースしました 🚀

[obsidian-day-planner](https://github.com/ivan-lednev/obsidian-day-planner) の形式を想定した挙動にしています。気になる点ありましたら別途コメントいただければと思います。

**Comment by masaki39** [comment]
早速ありがとうございます！
まさに望んでいたものとなりました！

2024年8月8日(木) 13:34 Tadashi Aikawa ***@***.***>:
