### ISSUE TITLE
Dailyノート内に付与したタスクの計算時間の総和をWeeklyノートに算出させたい

### ISSUE THREAD

**Issue by 1m-N00b** [tadashi-aikawa/silhouette#7]
素晴らしいプラグイン及びminervaでのtipsを拝見し、最近obsidianに流れ着いた者です。

この機能がほしい経緯としましては、週単位でのタスクのウェイトを知ることで,月末に見返す際や次週におけるタスク消化(Weeklyノートを加筆する時等)の整理がしやすいためです。
現状繋いでいるノートを開きタスク毎の時間を電卓で算出しているため、何か良い方法はないか,似たような話題がないか調べてみた所、似たようなものは見つけれたもののそういったプラグイン等はなかったため機能追加の要望として提案させて頂きました。
ご検討頂ければ幸いです。
よろしくお願いします。

似たような話題(Dateviewのため本質的には違うかもしれません)
- https://forum.obsidian.md/t/how-to-sum-dataview-values-of-a-certain-task-field-in-different-files/52877
- https://forum.obsidian.md/t/would-love-some-help-to-add-a-sum-total-to-my-dataview-query/76176

**Comment by tadashi-aikawa** [comment]
@1m-N00b 
機能提案ありがとうございます :)

Silhouetteは一度Daily noteに記載されたタスクの同一性を担保していないため、提案いただいた機能を実装することはないと思います。(タスクの測定も、タスクの内容は参照してなく、同一行に表示されている計測中/計測完了の文字で判定しているだけです)

もしTemplaterをお使いで、Daily Noteの形式が分かればお手伝いはできるかもしれません。興味ありましたら返信いただければと思います。

**Comment by 1m-N00b** [comment]
返信有難うございます。つい最近obsidianに使い始めたためまだテンプレやプラグインだったりの環境設定周りを固める段階のため具体的なテンプレは現状無い次第です。
因みに質問という形で申し訳ないのですが、各DailyをWeeklyに紐付ける(Link)を考えているのですが、このようなリンク先内にあるSilhouetteで計測したタスク名毎の個々のタスク時間を取得みたいなのはリンク親であるWeeklyから可能なのでしょうか

**Weekly**
```md
#### Daily Link
[[2024/09/09]]
[[2024/09/10]]
[[2024/09/11]]
[[2024/09/12]]
[[2024/09/13]]
[[2024/09/14]]
[[2024/09/15]]
```

**Daily**
```md
- [] Task A(⏲️01:23:45)
- [] Task B(⏲️01:23:45)
```

**Comment by tadashi-aikawa** [comment]
TemplaterやQuickAddのようにJavaScriptのスクリプトを書いて実行すれば可能だと思います。

**Comment by 1m-N00b** [comment]
助言有難うございます。
Templaterのドキュメント見て出来そうならやってみようと思います。
