### ISSUE TITLE
月と日を指定したタスク

### ISSUE THREAD

**Issue by gnnk** [tadashi-aikawa/silhouette#8]
月と日でタスクを指定できるようにしたいです。

現状、例えば、年に一回のタスクを設定したい場合、

every 365 day としたら、それに近い設定は可能なのですが、

4年に一度ずれてしまいます。

**Comment by tadashi-aikawa** [comment]
@gnnk 
機能提案ありがとうございます。

毎年繰り返すタスクは使う機会がなかったので対応していませんでしたが、必要とのことですので機能追加してみます 👍

**Comment by tadashi-aikawa** [comment]
【経過】
silhouette-coreは対応完了。 `0728` のような繰り返し表現。

https://bsky.app/profile/tadashi-aikawa.bsky.social/post/3l7pltjhxoj2i

次は Silhouette 本体の更新を行います。(silhouette-core の取り込みを行っていないのでそこから)

**Comment by tadashi-aikawa** [comment]
@gnnk 
v0.24.0で対応しました。ご確認ください。
https://github.com/tadashi-aikawa/silhouette/releases/tag/0.24.0

> [!TIP]
> 複数指定する場合は、 `|` 区切りで複数パターン指定する必要があります。 (例: `0828|0928` )

**Comment by gnnk** [comment]
ご対応ありがとうございます。

試してみたところ、
日時指定はMMDDの4桁表記にしてください
のエラーが表示されます。

MMDD以外の、例えばeveryday
といったタスク存在する場合にエラーとなってしまうようです。

**Comment by tadashi-aikawa** [comment]
@gnnk 
ご確認ありがとうございます。

> 例えばeveryday

`everyday` ではなく `every day` にして試していただけますでしょうか。

※ `everyday` というパターンはサポートしていません ( [参考](https://github.com/tadashi-aikawa/silhouette?tab=readme-ov-file#%E7%B9%B0%E3%82%8A%E8%BF%94%E3%81%97%E3%83%91%E3%82%BF%E3%83%BC%E3%83%B3) )
※ もともと『未サポートの文字列を指定すると毎日扱いになってしまう』という問題はありましたが、今回の改修でそれがエラーになるよう処理が変わったためです (『対応していないパターンです』のようなエラーにはしたいですが)

**Comment by gnnk** [comment]
ありがとうございます。

無事、動作することを確認いたしました。

**Comment by tadashi-aikawa** [comment]
【共有】 @gnnk 
以前よりも繰り返しパターンのエラー強化した v0.26.0 をリリースしました。よろしければお試しください。
https://github.com/tadashi-aikawa/silhouette/releases/tag/0.26.0
