### ISSUE TITLE
予定日後の稼働日に

### ISSUE THREAD

**Issue by rakugakijin** [tadashi-aikawa/silhouette#9]
毎月予定日の処理で、その日が稼働日じゃないことも出てきます。その際に、その後の稼働日に日にちをずらして表示することは可能ですか？

**Comment by tadashi-aikawa** [comment]
@rakugakijin 
今はできません。ただ、よく使う表現だと思いますので対応してみます。

**Comment by tadashi-aikawa** [comment]
【経過】
Silhouette Coreの対応が完了。Silhouette本体の方に取り込む。
https://github.com/tadashi-aikawa/silhouette-core/releases/tag/v1.2.0

**Comment by tadashi-aikawa** [comment]
@rakugakijin 
[v0.25.0](https://github.com/tadashi-aikawa/silhouette/releases/tag/0.25.0) で対応しました。ご確認ください。

以下はパターンの一例です。

- `10d>!` 毎月10日、その日が稼働日でない場合は翌稼働日
- `0702<!` 毎年7月2日、その日が稼働日でない場合は前稼働日
- `wed>!` 毎週水曜、その日が稼働日でない場合は翌稼働日
- `2mon<!` 毎月第2月曜、その日が稼働日でない場合は前稼働日

仕様や例は [README](https://github.com/tadashi-aikawa/silhouette?tab=readme-ov-file#%E3%82%AA%E3%83%95%E3%82%BB%E3%83%83%E3%83%88) の方に記載しておりますので、あわせてご覧ください。

**Comment by rakugakijin** [comment]
早速の対応ありがとうございます。

silhouette: insert taskで、

［Error］ Error：日時指定はMMDDの4桁表記にしてください（例： 0828）
が出ました。
出る原因を教えてください。

**Comment by tadashi-aikawa** [comment]
@rakugakijin 
以下ご確認ください。
https://github.com/tadashi-aikawa/silhouette/issues/8#issuecomment-2447458043

**Comment by rakugakijin** [comment]
> @rakugakijin 
> 
> 以下ご確認ください。
> 
> https://github.com/tadashi-aikawa/silhouette/issues/8#issuecomment-2447458043

確認しました。
原因は、末尾にスペースがはいってたことでした。
"every day"であるべきところ
"every day "と余分なスペースがありました。

ありがとうございました。

**Comment by tadashi-aikawa** [comment]
【共有】 @rakugakijin 
以前よりも繰り返しパターンのエラー強化した v0.26.0 をリリースしました。よろしければお試しください。
https://github.com/tadashi-aikawa/silhouette/releases/tag/0.26.0
